export default{
    "世足賽": {
        "世足賽": [
            {
                "4E1evvDQf6s": {
                    "keyword": "世足賽",
                    "subKeyword": "世足賽",
                    "channelId": "UCl_q5BsL1AOJNSQnjoyVsGA",
                    "channelTitle": "Matchday",
                    "vidTitle": "英格蘭vs法國 2022卡達世足賽八強戰淘汰賽",
                    "avg_sentiment": 0.7788319356505571,
                    "thumbnail": "https://i.ytimg.com/vi/4E1evvDQf6s/hqdefault.jpg",
                    "channel_chart": {
                        "categories": [
                            "Sports_game",
                            "Video_game_culture",
                            "Association_football",
                            "Sport"
                        ],
                        "viewcount": [
                            1035803,
                            865312,
                            167992,
                            130536
                        ],
                        "videocount": [
                            189,
                            119,
                            61,
                            36
                        ]
                    },
                    "total_view": 2199643,
                    "total_video": 405,
                    "com_bar": [
                        0,
                        0,
                        0,
                        0,
                        0,
                        1,
                        0,
                        1,
                        1,
                        1
                    ],
                    "total_com": 4
                }
            },
            {
                "2We3fhYFEFo": {
                    "keyword": "世足賽",
                    "subKeyword": "世足賽",
                    "channelId": "UCl_q5BsL1AOJNSQnjoyVsGA",
                    "channelTitle": "Matchday",
                    "vidTitle": "荷蘭vs阿根廷 2022卡達世足賽八強戰淘汰賽",
                    "avg_sentiment": 0.6029757363908594,
                    "thumbnail": "https://i.ytimg.com/vi/2We3fhYFEFo/hqdefault.jpg",
                    "channel_chart": {
                        "categories": [
                            "Sports_game",
                            "Video_game_culture",
                            "Association_football",
                            "Sport"
                        ],
                        "viewcount": [
                            1035803,
                            865312,
                            167992,
                            130536
                        ],
                        "videocount": [
                            189,
                            119,
                            61,
                            36
                        ]
                    },
                    "total_view": 2199643,
                    "total_video": 405,
                    "com_bar": [
                        0,
                        0,
                        0,
                        0,
                        0,
                        1,
                        0,
                        1,
                        0,
                        0
                    ],
                    "total_com": 2
                }
            },
            {
                "XTIddFJvcg8": {
                    "keyword": "世足賽",
                    "subKeyword": "世足賽",
                    "channelId": "UCl_q5BsL1AOJNSQnjoyVsGA",
                    "channelTitle": "Matchday",
                    "vidTitle": "克羅埃西亞vs巴西  2022卡達世足賽八強戰淘汰賽",
                    "avg_sentiment": 0.5244475105596396,
                    "thumbnail": "https://i.ytimg.com/vi/XTIddFJvcg8/hqdefault.jpg",
                    "channel_chart": {
                        "categories": [
                            "Sports_game",
                            "Video_game_culture",
                            "Association_football",
                            "Sport"
                        ],
                        "viewcount": [
                            1035803,
                            865312,
                            167992,
                            130536
                        ],
                        "videocount": [
                            189,
                            119,
                            61,
                            36
                        ]
                    },
                    "total_view": 2199643,
                    "total_video": 405,
                    "com_bar": [
                        0,
                        1,
                        1,
                        0,
                        1,
                        3,
                        0,
                        1,
                        0,
                        1
                    ],
                    "total_com": 8
                }
            },
            {
                "3FwxwIVoGns": {
                    "keyword": "世足賽",
                    "subKeyword": "世足賽",
                    "channelId": "UCR3asjvr_WAaxwJYEDV_Bfw",
                    "channelTitle": "東森新聞 CH51",
                    "vidTitle": "獨家》拉高賠率吸賭客 世足賽非法賭盤恐吸上億金流@newsebc",
                    "avg_sentiment": 0.5447537969174968,
                    "thumbnail": "https://i.ytimg.com/vi/3FwxwIVoGns/hqdefault.jpg",
                    "channel_chart": {
                        "categories": [
                            "Politics",
                            "Society",
                            "Food",
                            "Lifestyle_(sociology)",
                            "Television_program",
                            "Entertainment",
                            "Classical_music",
                            "Music",
                            "Pet",
                            "Basketball",
                            "Religion",
                            "Vehicle",
                            "Tourism",
                            "Hobby",
                            "Knowledge",
                            "Volleyball",
                            "Sport",
                            "Performing_arts",
                            "Film",
                            "Music_of_Asia"
                        ],
                        "viewcount": [
                            1201232,
                            13325630,
                            548147,
                            958220,
                            2859554,
                            429817,
                            9907,
                            21988,
                            347425,
                            14473,
                            44339,
                            11914,
                            4649,
                            4456,
                            27562,
                            2442,
                            4882,
                            1766,
                            1381,
                            1084
                        ],
                        "videocount": [
                            92,
                            820,
                            45,
                            69,
                            68,
                            17,
                            1,
                            3,
                            16,
                            3,
                            4,
                            4,
                            2,
                            2,
                            4,
                            1,
                            1,
                            1,
                            1,
                            1
                        ]
                    },
                    "total_view": 19820868,
                    "total_video": 1155,
                    "com_bar": [
                        0,
                        0,
                        0,
                        0,
                        0,
                        1,
                        0,
                        0,
                        0,
                        0
                    ],
                    "total_com": 1
                }
            }
        ],
        "台灣": [
            {
                "UBq4a5meQkU": {
                    "keyword": "世足賽",
                    "subKeyword": "台灣",
                    "channelId": "UC3N27-RTtmT2TKQKJi2X2wg",
                    "channelTitle": "台灣數位外交協會",
                    "vidTitle": "World Cup Taiwan 2022 台灣版世足賽精華！",
                    "avg_sentiment": 0.9405491844562781,
                    "thumbnail": "https://i.ytimg.com/vi/UBq4a5meQkU/hqdefault.jpg",
                    "channel_chart": {
                        "categories": [
                            "Society",
                            "Association_football",
                            "Sport",
                            "Lifestyle_(sociology)",
                            "Pet",
                            "Politics",
                            "Tourism",
                            "Knowledge",
                            "Hobby"
                        ],
                        "viewcount": [
                            7022,
                            27001,
                            27001,
                            2580,
                            105,
                            60,
                            642,
                            329,
                            210
                        ],
                        "videocount": [
                            18,
                            15,
                            15,
                            3,
                            1,
                            1,
                            3,
                            2,
                            1
                        ]
                    },
                    "total_view": 64950,
                    "total_video": 59,
                    "com_bar": [
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        1
                    ],
                    "total_com": 1
                }
            },
            {
                "uzDNHDXFBNQ": {
                    "keyword": "世足賽",
                    "subKeyword": "台灣",
                    "channelId": "UC2TuODJhC03pLgd6MpWP0iw",
                    "channelTitle": "三立LIVE新聞",
                    "vidTitle": "全球瘋世足! 世界盃足球賽8強今晚登場 \"人類章魚哥\"薩頓預測巴.荷.摩.法將晉級4強│記者 鄭凱中│【LIVE大現場】2022│三立新聞台",
                    "thumbnail": "https://i.ytimg.com/vi/uzDNHDXFBNQ/hqdefault.jpg",
                    "avg_sentiment": 0.6005594738953631,
                    "channel_chart": {
                        "categories": [
                            "Society",
                            "Politics",
                            "Pet",
                            "Food",
                            "Lifestyle_(sociology)",
                            "Religion",
                            "Vehicle",
                            "Television_program",
                            "Baseball",
                            "Basketball",
                            "Performing_arts",
                            "Music",
                            "Sport",
                            "Technology"
                        ],
                        "viewcount": [
                            15686614,
                            2537236,
                            11275,
                            54267,
                            76913,
                            42745,
                            30413,
                            40507,
                            7973,
                            1240,
                            245,
                            3345,
                            4747,
                            2231
                        ],
                        "videocount": [
                            924,
                            155,
                            4,
                            14,
                            22,
                            5,
                            2,
                            5,
                            3,
                            1,
                            1,
                            1,
                            2,
                            1
                        ]
                    },
                    "total_view": 18499751,
                    "total_video": 1140,
                    "com_bar": [
                        3,
                        2,
                        1,
                        1,
                        1,
                        6,
                        5,
                        2,
                        5,
                        5
                    ],
                    "total_com": 31
                }
            },
            {
                "VhaWw-4-ROM": {
                    "keyword": "世足賽",
                    "subKeyword": "台灣",
                    "channelId": "UC2TuODJhC03pLgd6MpWP0iw",
                    "channelTitle": "三立LIVE新聞",
                    "vidTitle": "世足賽最新戰報! 阿根廷逆勢突破\"16強將對澳洲\" E組\"死亡之組\"四搶二 F組比利時恐遭淘汰?｜主播 鄭凱中 鄧崴｜【LIVE大現場】20221201｜三立新聞台",
                    "avg_sentiment": 0.44515397451519434,
                    "thumbnail": "https://i.ytimg.com/vi/VhaWw-4-ROM/hqdefault.jpg",
                    "channel_chart": {
                        "categories": [
                            "Society",
                            "Politics",
                            "Pet",
                            "Food",
                            "Lifestyle_(sociology)",
                            "Religion",
                            "Vehicle",
                            "Television_program",
                            "Baseball",
                            "Basketball",
                            "Performing_arts",
                            "Music",
                            "Sport",
                            "Technology"
                        ],
                        "viewcount": [
                            15686614,
                            2537236,
                            11275,
                            54267,
                            76913,
                            42745,
                            30413,
                            40507,
                            7973,
                            1240,
                            245,
                            3345,
                            4747,
                            2231
                        ],
                        "videocount": [
                            924,
                            155,
                            4,
                            14,
                            22,
                            5,
                            2,
                            5,
                            3,
                            1,
                            1,
                            1,
                            2,
                            1
                        ]
                    },
                    "total_view": 18499751,
                    "total_video": 1140,
                    "com_bar": [
                        0,
                        1,
                        0,
                        0,
                        0,
                        0,
                        1,
                        0,
                        0,
                        0
                    ],
                    "total_com": 2
                }
            },
            {
                "wyKOv1pocsI": {
                    "keyword": "世足賽",
                    "subKeyword": "台灣",
                    "channelId": "UCL0_NxCvkcXwZHpvqgMZY-A",
                    "channelTitle": "TVBS選新聞",
                    "vidTitle": "瘋足球! 四年一次世足賽開踢 台灣有望掀起足球熱｜十點不一樣20221121",
                    "avg_sentiment": 0.5805229540573168,
                    "thumbnail": "https://i.ytimg.com/vi/wyKOv1pocsI/hqdefault.jpg",
                    "channel_chart": {
                        "categories": [
                            "Society",
                            "Entertainment",
                            "Film",
                            "Television_program",
                            "Politics",
                            "Baseball",
                            "Lifestyle_(sociology)",
                            "Basketball",
                            "Tourism",
                            "Association_football",
                            "Music",
                            "Music_of_Asia",
                            "Religion",
                            "Vehicle",
                            "Hobby",
                            "Pet",
                            "Military",
                            "Sport",
                            "Food",
                            "Health",
                            "Knowledge",
                            "Performing_arts",
                            "Video_game_culture",
                            "Pop_music",
                            "Motorsport"
                        ],
                        "viewcount": [
                            2266823,
                            12681,
                            3046,
                            95462,
                            1081429,
                            15523,
                            30023,
                            170308,
                            3781,
                            23911,
                            7811,
                            6513,
                            4289,
                            4447,
                            1106,
                            1364,
                            10870,
                            9783,
                            3760,
                            1121,
                            199,
                            190,
                            680,
                            74,
                            2120
                        ],
                        "videocount": [
                            786,
                            15,
                            7,
                            43,
                            192,
                            6,
                            25,
                            5,
                            3,
                            10,
                            5,
                            4,
                            5,
                            4,
                            2,
                            3,
                            3,
                            6,
                            6,
                            2,
                            1,
                            1,
                            1,
                            1,
                            1
                        ]
                    },
                    "total_view": 3757314,
                    "total_video": 1137,
                    "com_bar": [
                        0,
                        0,
                        0,
                        0,
                        0,
                        1,
                        0,
                        0,
                        0,
                        0
                    ],
                    "total_com": 1
                }
            }
        ]
    },
    "疫情": {
        "中心": [
            {
                "Spaj3pm6iWg": {
                    "keyword": "疫情",
                    "subKeyword": "中心",
                    "channelId": "UCyh91eTE9jA3ykg8W3_v3DQ",
                    "channelTitle": "衛生福利部疾病管制署",
                    "vidTitle": "2022/10/12 14:00 中央流行疫情指揮中心嚴重特殊傳染性肺炎記者會",
                    "avg_sentiment": 0.5837200288841922,
                    "thumbnail": "https://i.ytimg.com/vi/Spaj3pm6iWg/hqdefault.jpg",
                    "channel_chart": {
                        "categories": [
                            "Society",
                            "Entertainment",
                            "Film",
                            "Health",
                            "Lifestyle_(sociology)",
                            "Knowledge",
                            "Music",
                            "Tennis",
                            "Television_program",
                            "Action-adventure_game",
                            "Action_game",
                            "Puzzle_video_game",
                            "Video_game_culture",
                            "Tourism",
                            "Performing_arts",
                            "Food",
                            "Technology",
                            "Politics",
                            "Music_of_Asia",
                            "Baseball",
                            "Sport",
                            "Business"
                        ],
                        "viewcount": [
                            45805886,
                            220441,
                            90235,
                            225468,
                            77702,
                            493198,
                            10040,
                            502,
                            2411,
                            2962,
                            2962,
                            2962,
                            8045,
                            4365,
                            120,
                            397,
                            161,
                            75744,
                            1108,
                            2688,
                            2688,
                            6124
                        ],
                        "videocount": [
                            455,
                            57,
                            30,
                            19,
                            18,
                            67,
                            6,
                            1,
                            4,
                            1,
                            1,
                            1,
                            3,
                            3,
                            1,
                            1,
                            1,
                            2,
                            1,
                            1,
                            1,
                            1
                        ]
                    },
                    "total_view": 47036209,
                    "total_video": 675,
                    "com_bar": [
                        1,
                        1,
                        1,
                        0,
                        2,
                        1,
                        2,
                        2,
                        0,
                        3
                    ],
                    "total_com": 13
                }
            },
            {
                "IIxdquHipQE": {
                    "keyword": "疫情",
                    "subKeyword": "中心",
                    "channelId": "UCyh91eTE9jA3ykg8W3_v3DQ",
                    "channelTitle": "衛生福利部疾病管制署",
                    "vidTitle": "2022/10/25 14:00 中央流行疫情指揮中心嚴重特殊傳染性肺炎記者會",
                    "avg_sentiment": 0.5233730715176155,
                    "thumbnail": "https://i.ytimg.com/vi/IIxdquHipQE/hqdefault.jpg",
                    "channel_chart": {
                        "categories": [
                            "Society",
                            "Entertainment",
                            "Film",
                            "Health",
                            "Lifestyle_(sociology)",
                            "Knowledge",
                            "Music",
                            "Tennis",
                            "Television_program",
                            "Action-adventure_game",
                            "Action_game",
                            "Puzzle_video_game",
                            "Video_game_culture",
                            "Tourism",
                            "Performing_arts",
                            "Food",
                            "Technology",
                            "Politics",
                            "Music_of_Asia",
                            "Baseball",
                            "Sport",
                            "Business"
                        ],
                        "viewcount": [
                            45805886,
                            220441,
                            90235,
                            225468,
                            77702,
                            493198,
                            10040,
                            502,
                            2411,
                            2962,
                            2962,
                            2962,
                            8045,
                            4365,
                            120,
                            397,
                            161,
                            75744,
                            1108,
                            2688,
                            2688,
                            6124
                        ],
                        "videocount": [
                            455,
                            57,
                            30,
                            19,
                            18,
                            67,
                            6,
                            1,
                            4,
                            1,
                            1,
                            1,
                            3,
                            3,
                            1,
                            1,
                            1,
                            2,
                            1,
                            1,
                            1,
                            1
                        ]
                    },
                    "total_view": 47036209,
                    "total_video": 675,
                    "com_bar": [
                        2,
                        1,
                        1,
                        0,
                        1,
                        0,
                        2,
                        1,
                        0,
                        3
                    ],
                    "total_com": 11
                }
            },
            {
                "MCK5FiKtDUw": {
                    "keyword": "疫情",
                    "subKeyword": "中心",
                    "channelId": "UCyh91eTE9jA3ykg8W3_v3DQ",
                    "channelTitle": "衛生福利部疾病管制署",
                    "vidTitle": "2022/12/5 14:00 中央流行疫情指揮中心嚴重特殊傳染性肺炎記者會",
                    "avg_sentiment": 0.7406800836432698,
                    "thumbnail": "https://i.ytimg.com/vi/MCK5FiKtDUw/hqdefault.jpg",
                    "channel_chart": {
                        "categories": [
                            "Society",
                            "Entertainment",
                            "Film",
                            "Health",
                            "Lifestyle_(sociology)",
                            "Knowledge",
                            "Music",
                            "Tennis",
                            "Television_program",
                            "Action-adventure_game",
                            "Action_game",
                            "Puzzle_video_game",
                            "Video_game_culture",
                            "Tourism",
                            "Performing_arts",
                            "Food",
                            "Technology",
                            "Politics",
                            "Music_of_Asia",
                            "Baseball",
                            "Sport",
                            "Business"
                        ],
                        "viewcount": [
                            45805886,
                            220441,
                            90235,
                            225468,
                            77702,
                            493198,
                            10040,
                            502,
                            2411,
                            2962,
                            2962,
                            2962,
                            8045,
                            4365,
                            120,
                            397,
                            161,
                            75744,
                            1108,
                            2688,
                            2688,
                            6124
                        ],
                        "videocount": [
                            455,
                            57,
                            30,
                            19,
                            18,
                            67,
                            6,
                            1,
                            4,
                            1,
                            1,
                            1,
                            3,
                            3,
                            1,
                            1,
                            1,
                            2,
                            1,
                            1,
                            1,
                            1
                        ]
                    },
                    "total_view": 47036209,
                    "total_video": 675,
                    "com_bar": [
                        0,
                        1,
                        0,
                        0,
                        0,
                        2,
                        1,
                        1,
                        1,
                        4
                    ],
                    "total_com": 10
                }
            },
            {
                "6UHf_Zb4wpE": {
                    "keyword": "疫情",
                    "subKeyword": "中心",
                    "channelId": "UCyh91eTE9jA3ykg8W3_v3DQ",
                    "channelTitle": "衛生福利部疾病管制署",
                    "vidTitle": "2022/10/24 14:00 中央流行疫情指揮中心嚴重特殊傳染性肺炎記者會",
                    "avg_sentiment": 0.45998528286925017,
                    "thumbnail": "https://i.ytimg.com/vi/6UHf_Zb4wpE/hqdefault.jpg",
                    "channel_chart": {
                        "categories": [
                            "Society",
                            "Entertainment",
                            "Film",
                            "Health",
                            "Lifestyle_(sociology)",
                            "Knowledge",
                            "Music",
                            "Tennis",
                            "Television_program",
                            "Action-adventure_game",
                            "Action_game",
                            "Puzzle_video_game",
                            "Video_game_culture",
                            "Tourism",
                            "Performing_arts",
                            "Food",
                            "Technology",
                            "Politics",
                            "Music_of_Asia",
                            "Baseball",
                            "Sport",
                            "Business"
                        ],
                        "viewcount": [
                            45805886,
                            220441,
                            90235,
                            225468,
                            77702,
                            493198,
                            10040,
                            502,
                            2411,
                            2962,
                            2962,
                            2962,
                            8045,
                            4365,
                            120,
                            397,
                            161,
                            75744,
                            1108,
                            2688,
                            2688,
                            6124
                        ],
                        "videocount": [
                            455,
                            57,
                            30,
                            19,
                            18,
                            67,
                            6,
                            1,
                            4,
                            1,
                            1,
                            1,
                            3,
                            3,
                            1,
                            1,
                            1,
                            2,
                            1,
                            1,
                            1,
                            1
                        ]
                    },
                    "total_view": 47036209,
                    "total_video": 675,
                    "com_bar": [
                        2,
                        0,
                        2,
                        2,
                        3,
                        3,
                        1,
                        1,
                        0,
                        2
                    ],
                    "total_com": 16
                }
            }
        ],
        "疫苗": [
            {
                "R6P01CKD5G4": {
                    "keyword": "疫情",
                    "subKeyword": "疫苗",
                    "channelId": "UCaHvWPMrGgcd42waw4WYQ6w",
                    "channelTitle": "從台灣看見世界的故事",
                    "vidTitle": "拜登宣布\"疫情大流行\"結束！ 美國疫苗股莫德納跌超過7%.輝瑞跌1.28% 中國持續\"清零政策\"引民怨｜【國際大現場】20220920｜三立新聞台",
                    "avg_sentiment": 0.7226636980099032,
                    "thumbnail": "https://i.ytimg.com/vi/R6P01CKD5G4/hqdefault.jpg",
                    "channel_chart": {
                        "categories": [
                            "Society",
                            "Television_program",
                            "Food",
                            "Lifestyle_(sociology)",
                            "Politics",
                            "Tourism",
                            "Pet",
                            "Tennis",
                            "Music",
                            "Technology",
                            "Film",
                            "Professional_wrestling",
                            "Association_football",
                            "Baseball",
                            "Hobby",
                            "Vehicle",
                            "Music_of_Asia",
                            "Knowledge",
                            "Entertainment",
                            "Sport",
                            "Hip_hop_music"
                        ],
                        "viewcount": [
                            27228450,
                            7941253,
                            297588,
                            2326575,
                            4086578,
                            180188,
                            5852,
                            28418,
                            31326,
                            68161,
                            18531,
                            21386,
                            391572,
                            2621,
                            128063,
                            57359,
                            84891,
                            8449,
                            11881,
                            7572,
                            3190
                        ],
                        "videocount": [
                            864,
                            67,
                            18,
                            53,
                            188,
                            11,
                            2,
                            6,
                            1,
                            1,
                            2,
                            1,
                            3,
                            3,
                            6,
                            3,
                            1,
                            1,
                            2,
                            1,
                            1
                        ]
                    },
                    "total_view": 42929904,
                    "total_video": 1235,
                    "com_bar": [
                        0,
                        0,
                        0,
                        2,
                        0,
                        1,
                        4,
                        4,
                        2,
                        3
                    ],
                    "total_com": 16
                }
            },
            {
                "IXcW9R6YmTU": {
                    "keyword": "疫情",
                    "subKeyword": "疫苗",
                    "channelId": "UCmgDmqjxbkqIXu4rNbrKodA",
                    "channelTitle": "TVBS 優選頻道",
                    "vidTitle": "BA.5讓歐美疫情再升溫 洛杉磯考慮重啟口罩令｜十點不一樣20220719",
                    "avg_sentiment": 0.4230561304017123,
                    "thumbnail": "https://i.ytimg.com/vi/IXcW9R6YmTU/hqdefault.jpg",
                    "channel_chart": {
                        "categories": [
                            "Politics",
                            "Society",
                            "Television_program",
                            "Food",
                            "Lifestyle_(sociology)",
                            "Entertainment",
                            "Film",
                            "Business",
                            "Music",
                            "Pet",
                            "Health",
                            "Sport",
                            "Association_football",
                            "Music_of_Asia",
                            "Tourism",
                            "Performing_arts",
                            "Hobby",
                            "Religion",
                            "Classical_music",
                            "Physical_fitness",
                            "Pop_music",
                            "Rock_music",
                            "Basketball",
                            "Military",
                            "Technology",
                            "Baseball"
                        ],
                        "viewcount": [
                            932847,
                            12378438,
                            7550285,
                            460064,
                            1983330,
                            3317817,
                            1017879,
                            9466,
                            10445,
                            26671,
                            103955,
                            311,
                            14808,
                            429028,
                            33928,
                            7449,
                            20260,
                            10040,
                            2401,
                            12492,
                            6606,
                            6606,
                            158154,
                            215011,
                            16175,
                            2879
                        ],
                        "videocount": [
                            101,
                            746,
                            166,
                            32,
                            53,
                            51,
                            18,
                            2,
                            4,
                            2,
                            8,
                            1,
                            2,
                            7,
                            9,
                            2,
                            6,
                            1,
                            1,
                            1,
                            1,
                            1,
                            2,
                            4,
                            3,
                            1
                        ]
                    },
                    "total_view": 28727345,
                    "total_video": 1225,
                    "com_bar": [
                        0,
                        0,
                        0,
                        0,
                        1,
                        0,
                        0,
                        0,
                        0,
                        0
                    ],
                    "total_com": 1
                }
            },
            {
                "e9DeXxKK_-E": {
                    "keyword": "疫情",
                    "subKeyword": "疫苗",
                    "channelId": "UC5nwNW4KdC0SzrhF9BXEYOQ",
                    "channelTitle": "TVBS NEWS",
                    "vidTitle": "BA.5讓歐美疫情再升溫 洛杉磯考慮重啟口罩令｜十點不一樣20220719",
                    "avg_sentiment": 0.5454194957121272,
                    "thumbnail": "https://i.ytimg.com/vi/e9DeXxKK_-E/hqdefault.jpg",
                    "channel_chart": {
                        "categories": [
                            "Society",
                            "Politics",
                            "Film",
                            "Entertainment",
                            "Television_program",
                            "Food",
                            "Lifestyle_(sociology)",
                            "Health",
                            "Association_football",
                            "Sport",
                            "Vehicle",
                            "Basketball",
                            "Tourism",
                            "Pet",
                            "Rock_music",
                            "Business",
                            "Music",
                            "Music_of_Asia",
                            "Military",
                            "Hobby",
                            "Technology",
                            "Religion",
                            "Reggae",
                            "Fashion",
                            "Classical_music",
                            "Performing_arts",
                            "Pop_music"
                        ],
                        "viewcount": [
                            9288324,
                            1407630,
                            7696,
                            308632,
                            254385,
                            272444,
                            506491,
                            15859,
                            54874,
                            13419,
                            103802,
                            297067,
                            7515,
                            26503,
                            32048,
                            203,
                            38130,
                            20425,
                            56170,
                            30875,
                            1449,
                            3239,
                            3027,
                            6980,
                            1352,
                            1352,
                            2396
                        ],
                        "videocount": [
                            733,
                            200,
                            4,
                            30,
                            37,
                            24,
                            71,
                            4,
                            9,
                            7,
                            8,
                            7,
                            6,
                            12,
                            1,
                            1,
                            8,
                            3,
                            2,
                            3,
                            1,
                            3,
                            1,
                            1,
                            1,
                            1,
                            1
                        ]
                    },
                    "total_view": 12762287,
                    "total_video": 1179,
                    "com_bar": [
                        0,
                        0,
                        0,
                        0,
                        1,
                        1,
                        1,
                        0,
                        0,
                        0
                    ],
                    "total_com": 3
                }
            },
            {
                "LIHGTrlWyAo": {
                    "keyword": "疫情",
                    "subKeyword": "疫苗",
                    "channelId": "UC_iwP8I13JnL54BypRCzldw",
                    "channelTitle": "老天鵝娛樂",
                    "vidTitle": "新台灣模式／東南水泥廠施工意外／0406台灣疫情｜老鵝特搜#814",
                    "avg_sentiment": 0.6246278204066863,
                    "thumbnail": "https://i.ytimg.com/vi/LIHGTrlWyAo/hqdefault.jpg",
                    "channel_chart": {
                        "categories": [
                            "Society",
                            "Politics",
                            "Entertainment",
                            "Television_program",
                            "Music",
                            "Music_of_Asia",
                            "Association_football",
                            "Food",
                            "Lifestyle_(sociology)",
                            "Film",
                            "Religion",
                            "Hobby",
                            "Vehicle",
                            "Basketball",
                            "Tennis",
                            "Action_game",
                            "Video_game_culture",
                            "Racing_video_game",
                            "Baseball",
                            "Sport",
                            "Technology",
                            "Pet",
                            "Action-adventure_game",
                            "Puzzle_video_game",
                            "Strategy_video_game",
                            "Hip_hop_music",
                            "Pop_music",
                            "Tourism",
                            "Electronic_music"
                        ],
                        "viewcount": [
                            80173753,
                            35296083,
                            7443997,
                            2646236,
                            8396575,
                            3653842,
                            79534,
                            32993,
                            354991,
                            1334953,
                            507567,
                            92512,
                            120027,
                            634481,
                            217178,
                            76278,
                            330573,
                            190787,
                            1345538,
                            396011,
                            44530,
                            7444,
                            4155,
                            4155,
                            4155,
                            20239,
                            381986,
                            21814,
                            498109
                        ],
                        "videocount": [
                            539,
                            209,
                            43,
                            21,
                            14,
                            4,
                            1,
                            3,
                            13,
                            4,
                            3,
                            1,
                            3,
                            6,
                            2,
                            2,
                            4,
                            1,
                            8,
                            2,
                            3,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            2,
                            1
                        ]
                    },
                    "total_view": 144310496,
                    "total_video": 895,
                    "com_bar": [
                        17,
                        15,
                        26,
                        35,
                        45,
                        56,
                        59,
                        51,
                        41,
                        89
                    ],
                    "total_com": 434
                }
            }
        ]
    }
}